server:
  port: 8080  # Spring boot Server port

spring:
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: